### ISSUE TITLE
[Question] Building or Running on all platforms

### ISSUE THREAD

**Issue by legendarynacar** [alexanderwe/checksum-validator#19]
Since it is only being published a builded version for MacOSX, what about just running under npm on other platforms (Windows, Linux distro's). If it is possible, can you make a guide?

**Comment by alexanderwe** [comment]
I already thought about releasing versions for other operating systems. Currently checksum-validator uses some native MacOs command line tools to calculate the checksums. I would have to find replacements for them on other OS or switch to Javascript implementations of the hashing algorithm. Currently I do not have the time to look further into it, but in around 1 month I should have some free time to evaluate this. Would be happy to release it on other platforms as well. 

I will make your issue a feature request so I can keep track of it !

**Comment by alexanderwe** [comment]
Application now available on Win and Linux
